### ISSUE TITLE
Slider Libs

### ISSUE THREAD

**Issue by therealansh** [dsciiitsonepat/dsc-iiits#10]
Discuss different slider libs here.  Rn we are using SwiperJS

Problems faced rn:
- Docs
- Usability
- Does not go well with the design

If you can build up a swiping effect wrapper let me know. The transition should be minimal.

**Comment by VanshKela** [comment]
Can I work on this issue?

**Comment by quirked** [comment]
Can i do this?

**Comment by therealansh** [comment]
#21 closes this issue
