### ISSUE TITLE
HomePage Styling in Mobile

### ISSUE THREAD

**Issue by therealansh** [dsciiitsonepat/dsc-iiits#24]
[TODO]:

- [ ] the circular logo right now is just a work around. In responsive we have just hid the actual logo and added it in home page. We need to find a robust solution for production and center it.
- [ ] The HomePage Container div is also not centered in mobile view.

**Comment by therealansh** [comment]
Work on checking branch out from `origin/mobile`

**Comment by VanshKela** [comment]
can i work on this?

**Comment by aneeshsharma0671** [comment]
![X - 1](https://user-images.githubusercontent.com/54682356/128630087-95dec219-f59c-4f42-9ca7-827b60b310cf.png)
@VanshKela for styling take refrence from this mockup
