### ISSUE TITLE
Event Card Responsive design

### ISSUE THREAD

**Issue by therealansh** [dsciiitsonepat/dsc-iiits#31]
Style the event card responsive. Remember that null is media so make space accordingly.

**Comment by VermaShivansh** [comment]
Can I work on this?

**Comment by AdityaChaudhary18** [comment]
Can i work on this ?

**Comment by aneeshsharma0671** [comment]
@AdityaChaudhary18  for styling take refrence from this mockup
![X - 3](https://user-images.githubusercontent.com/54682356/128630174-e2307150-3e99-42e7-9dfb-b3d8307f7211.png)
