### ISSUE TITLE
Breathing animation 

### ISSUE THREAD

**Issue by therealansh** [dsciiitsonepat/dsc-iiits#9]
Its kinda sudden and jerky at the end of the animation. smother it up.

**Comment by VanshKela** [comment]
Can I work on this issue?

**Comment by aneeshsharma0671** [comment]
@VanshKela just add keyframes at 50%,75%,100% alternating to .9 and 1, and keep same keyframes at 0% and 100%

**Comment by aneeshsharma0671** [comment]
@VanshKela this issue is resolved just a minor change in keyframes was required
